### PR TITLE
Proposal for a new description and link for ArcGIS

### PR DESCRIPTION
**Pull request by hhkaos**
As I mentioned on [this comment](https://github.com/sshuair/awesome-gis/commit/13e2d56d41adc1a0c4a5df59139db737d08f5d3d#r36589341), I wouldn't describe ArcGIS like "a desktop GIS software" anymore, and the link is pointing to "www.arcgis.com" which is the landing page for "ArcGIS Online", the cloud service, the official page is [esri.com/arcgis](https://www.esri.com/arcgis).

I have spent some time working [a diagram to describe the ecosystem of technologies that form the Esri platform](https://docs.google.com/drawings/d/1w_tBCVPdPULUehfFBJaqyH7ywZyxZLBCeemWFa3o2Ho/edit?usp=sharing), and based on my experience, I think it would make more sense to change the description to "Cross-platform with free, open and paid data and mapping tools, APIs, SDKs, etc."? 

> Note: I would include "free" because there are more than 7000 curated datasets than can be used for free, but also a developer account that allow to use ArcGIS Online with 10 SDKs, 5 app builders, etc, [for free](https://developers.arcgis.com/pricing/) with a pay-as-you-go model that includes monthly credits to use APIs for free (for example to host +200MB of data in the free account).

Cheers!

### CODE REVIEW

**Comment by sshuair** [comment]
I agree the old link should be replaced. But the description including too many things. I supposed `Geographic Information System Software` should focus on Desktop Software, but not APIs, SDKs...
One more thing, is ArcGIS cross-platform(MacOS/Linux) now?

**Comment by hhkaos** [comment]
Aha, ok then the name of the section and other elements in the list (like GISInternals) confused me, I thought *Geographic Information System* in the broadest sense of the term, [like in the wikipedia]:(https://en.wikipedia.org/wiki/Geographic_information_system):
> *...tools that allow users to create interactive queries (user-created searches), analyze spatial information, edit data in maps, and present the results of all these operations*

Why not call it then *GIS Desktop Software* or just *Desktop Software*?

Having that in mind:

* I would replace [ArcGIS](https://www.esri.com/arcgis) by [ArcGIS Desktop](https://www.esri.com/en-us/arcgis/products/arcgis-desktop/overview). 
* You are right, ArcGIS Desktop is just for Windows. The only out of the box product (besides web and mobile apps) that runs on other OS is ArcGIS Enterprise, formerly called ArcGIS Server, which also runs on Linux. The technologies to build cross-platform tools are some of the SDKs like Qt, Java, and Xamarin.

So for ArcGIS Desktop, I would say: 

* **[ArcGIS Desktop](https://www.esri.com/en-us/arcgis/products/arcgis-desktop/overview)**: Extendable desktop suite to manage, visualize and analyze GIS data in 2D and 3D, including image processing. Includes ArcGIS Pro, ArcMap, ArcCatalog, and ArcGIS Online.

**Comment by sshuair** [comment]
That's sounds great, could you modify your PR?

**Comment by hhkaos** [comment]
Sure, done!

**Comment by hhkaos** [comment]
What do you think about replacing...

* `## Geographic Information System Software` 
* for: `## Desktop Software` 

? 😄

**Comment by sshuair** [comment]
How about ` GIS Desktop Software`?

**Pull request merged**
